devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPad Pro (12.9 inch)",
  "iPad Pro (9.7 inch)"
 ])

languages([
  "en-US", 
  "fr"
])

scheme "CocoaConfUITests"
clear_previous_screenshots true